### ISSUE TITLE
main.ipynb problem

### ISSUE THREAD

**Issue by 294486709** [Wwwzff/Ship-Detection#5]
For some reason i cannot load main.ipython on either my local machine or github through browser.

**Comment by 294486709** [comment]
Also, I found that I cannot create an issue to the  https://github.com/ethanhou99/Ship-Detection directly.
Maybe you should go to the settings page of your repo and check the box next to Issues.

**Comment by Wwwzff** [comment]
>           For some reason i cannot load main.ipython on either my local machine or github through browser.

Not sure if it will work but did you try jupyter notebook yet? It also happens when I try to gitclone others works. If it's still not working, you may leave your email and I just send it to you.
Regards

**Comment by 294486709** [comment]
Jupyter notebook works! Thanks.
